### ISSUE TITLE
"correlation" in calculate_metrics

### ISSUE THREAD

**Issue by QidiFeng** [dynverse/dyneval#56]
Hi, Dyneval group,

I tried to use "correlation" metric in calculate_metrics function. However, it reports that:
> calculate_metrics(dataset, model, metrics = dyneval::metrics$metric_id[1], expression_source = dataset$expression)
Error: is.null(model) || dynwrap::is_wrapper_with_waypoint_cells(model) isn't true.

I tried to figure out the problem by adding cell waypoints by:
> dataset <- add_cell_waypoints(dataset)
> model$model <- map(model$model, add_cell_waypoints)

However, the error still exist. There is no errors reporting when I used other metrics. So I supposed this is not the problem regarding dataset or model. So any suggestions? Thank you very much!

Best,
Qidi

**Comment by zouter** [comment]
Hi Qidi



You're almost there I think. What is exactly `model` in your case? Is this a dataframe retrieved by doing `infer_trajectories()` ?

**Comment by QidiFeng** [comment]
Hi Wouter,

The model is a dataframe but not retrieved by doing
infer_trajectories(). Since
I want to compare the performance of multiple dimension reduction methods
in trajectory inference, so I applied slingshot on results from multiple
dimension reduction methods, and then wrap the results from slingshot to
that model required by dynverse according to ti_slingshot.R in dynverse
github (The code is attached below). I also gave a model example in the
attachment. You may like to check it~

Code:
slingout <-
load(paste0(res_path,"slingshot.data",idata,".method",imethod,".RData"))
  #
____________________________________________________________________________
  #   Create output to dynverse model
                      ####

  # collect milestone network
  lineages <- slingLineages(slingout)
  lineage_ctrl <- slingParams(slingout)

  cluster_network <- lineages %>%
    map_df(~ tibble(from = .[-length(.)], to = .[-1])) %>%
    unique() %>%
    mutate(
      length = lineage_ctrl$dist[cbind(from, to)],
      directed = TRUE
    )

  # collect dimred
  dimred <- reducedDim(slingout)

  # collect clusters
  cluster <- slingClusterLabels(slingout)

  # collect progressions
  adj <- slingAdjacency(slingout)
  lin_assign <- apply(slingCurveWeights(slingout), 1, which.max)

  progressions <- map_df(seq_along(lineages), function(l) {
    ind <- lin_assign == l
    lin <- lineages[[l]]
    pst.full <- slingPseudotime(slingout, na = FALSE)[,l]
    pst <- pst.full[ind]
    means <- sapply(lin, function(clID){
      stats::weighted.mean(pst.full, cluster[,clID])
    })
    non_ends <- means[-c(1,length(means))]
    edgeID.l <- as.numeric(cut(pst, breaks = c(-Inf, non_ends, Inf)))
    from.l <- lineages[[l]][edgeID.l]
    to.l <- lineages[[l]][edgeID.l + 1]
    m.from <- means[from.l]
    m.to <- means[to.l]

    pct <- (pst - m.from) / (m.to - m.from)
    pct[pct < 0] <- 0
    pct[pct > 1] <- 1

    tibble(cell_id = names(which(ind)), from = from.l, to = to.l,
percentage = pct)
  })

  #
____________________________________________________________________________
  #   Save output
  ####
  model <-
    dynwrap::wrap_data(
      cell_ids = rownames(expression)
    ) %>%
    dynwrap::add_trajectory(
      milestone_network = cluster_network,
      progressions = progressions
    ) %>%
    dynwrap::add_dimred(
      dimred = dimred
    )
save(model, file=paste0(res_path,
"slingshot.model.data",idata,".method",imethod,".RData"))

**Comment by zouter** [comment]
Hi Qidi

So model is just one model, all you have to do is `model <- add_cell_waypoints(model)` :slightly_smiling_face:

**Comment by QidiFeng** [comment]
Great! That did solve the problem, thank you very much!

Best,
Qidi

**Comment by zouter** [comment]
Awesome!
